### ISSUE TITLE
The library `liblikwid`` couldn't be found. Don't expect anything to work.

### ISSUE THREAD

**Issue by albertomercurio** [JuliaPerf/LIKWID.jl#60]
Hello,

I was trying to install this package. I have first installed LIKWID from [this link](https://github.com/RRZE-HPC/likwid#download-build-and-install), and then I installed the Julia package as normal package.

I’m able to run LIKWID from terminal, for example the `likwid-topology` command. However, when I import it in Julia, it says

```julia-repl
julia> using LIKWID
┌ Warning: The library `liblikwid`` couldn't be found. Don't expect anything to work.
│   liblikwid = "liblikwid"
└ @ LIKWID ~/.julia/packages/LIKWID/XtIXd/src/LIKWID.jl:96
```

**Comment by carstenbauer** [comment]
Hey, is the directory that contains liblikwid on `LD_LIBRARY_PATH`? If so, Julia should be able to find it.

It would be nice to have a way to overwrite the automatic detection and to manually provide the path to the library (via Preferences). Not sure when I will get to it though.

**Comment by albertomercurio** [comment]
It wasn’t on `LD_LIBRARY_PATH`. I added it using `find /usr/local -name "liblikwid.so"`, finding the containing directory, and then doing `echo 'export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH' >> ~/.bashrc`.
