### ISSUE TITLE
Can I use LIKWID to analyze code run outside of Julia?

### ISSUE THREAD

**Issue by sloede** [JuliaPerf/LIKWID.jl#62]
We'd like to analyze the performance of OpenFHE.jl, which internally uses CxxWrap.jl to call functions in a BB-provided C++ library (OpenFHE). However, when I measure operations that clearly take non-negligible time, I always get a `RETIRED_SSE_AVX_FLOPS_ALL` value of zero, and also the FLOPs/s are zero.

Is it a tool-specific issue that we just need to figure out, or is this generally not possible to do with LIKWID.jl?

cc @arseniykholod

**Comment by vchuravy** [comment]
LIKWID set's up performance counters, the only thing that might happen is that OpenFHE uses threads internally? 

As an example to measure OpenBLAS one has to do something like https://github.com/JuliaPerf/LIKWID.jl/blob/83707dfd5845a3e1bf396309c89462f4e2e8c223/examples/dynamic/perfmon_openblas/perfmon_openblas.jl#L11

**Comment by sloede** [comment]
Thanks for the hint, we will take a look 👍

**Comment by carstenbauer** [comment]
To expand: LIKWID simply tracks what happens in certain CPU cores. Whatever runs on these cores - Julia or not Julia - will be measured.

When you use `@perfmon`, we auto-pin the Julia threads to some CPU-cores and then measure in these cores. OpenBLAS threads or, potentially, OpenFHE threads will not be auto-pinned and will likely run on other CPU cores. Hence, they don't influence the result.

In the example that Valentin linked, we tell LIKWID.jl explicitly which CPU-cores to monitor. For example, we could track the performance of all CPU-cores or we could select those on which the relevant threads are running (we could pin the OpenBLAS threads to a specific subset of the available cores).

**Comment by ArseniyKholod** [comment]
Thank you for your help!
Am I right that the OpenBLAS example already tracks all CPU cores by using `cpuids = 0:(nvcores - 1)` in `@perfmon`?

If not, what should I do to track all the cores?
Sorry, if the answer is obvious, I am using LIKWID for the first time.)

**Comment by carstenbauer** [comment]
> Am I right that the OpenBLAS example already tracks all CPU cores by using `cpuids = 0:(nvcores - 1)` in `@perfmon`?

Yes.
